name: 'Autoroute'
description: 'Autoroute a given DSN file to SES with FreeRouting'
inputs:
  boards:
    description: 'Specctra SES output file'
    required: true
runs:
  using: 'docker'
  image: 'docker://ghcr.io/freerouting/freerouting:2.2.4
'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      for board in ${{ inputs.boards }};
      do
        echo "Processing $board";
        if [ -e $GITHUB_WORKSPACE/output/pcbs/${board}.ses ]; then
          echo "Cleaning up $GITHUB_WORKSPACE/output/pcbs/${board}.ses";
          rm -f $GITHUB_WORKSPACE/output/pcbs/${board}.ses;
        fi
        if [ -e $GITHUB_WORKSPACE/output/pcbs/${board}.dsn ]; then
          echo "Autoroute PCB";
          java -jar /app/freerouting.jar -de $GITHUB_WORKSPACE/output/pcbs/${board}.dsn -do $GITHUB_WORKSPACE/output/pcbs/${board}.ses -dr $GITHUB_WORKSPACE/scripts/freerouting.rules --user-data-path $GITHUB_WORKSPACE/scripts -mp 25 -mt 1 -dct 0 --gui.enabled=false --profile.email=info@freerouting.app
        fi
      done
