meta:
  engine: 4.1.0
  name: ergo-k33b
  version: 0.1
  ref: &kb_ref "ErgoK33b v0.1"
  author: hastyrobot
  url: &kb_url https://github.com/acornejo/ergo-k33b

units:
  # Proxy Spacing Variables
  kx: u
  ky: u 
  # Padding Variables
  px: kx + 4
  py: ky + 4
  # key cutout hole size
  kcow: 14
  kcoh: 14

   # Physical measures
  screw_radius: 1.1 # M2 screws
  screw_diameter: screw_radius * 2
  screw_head_radius: 2.05
  screw_head_diameter: screw_head_radius * 2
  spacer_radius: 2.15 # M2 standoffs
  spacer_diameter: spacer_radius * 2

points:
  zones:
    # 6 x 4 matrix layout
    matrixkeys:
      # Fix placement on KiCAD sheet.
      anchor:
        shift: [100, -100]
      columns:
        outer:
          key:
            stagger: 0
            column_net: P0
        pinky:
          key:
            stagger: 2.5
            column_net: P16
        ring:
          key:
            stagger: 5
            column_net: P14
        middle:
          key:
            stagger: 2.5
            column_net: P15
        index:
          key:
            stagger: -2.5
            column_net: P18
        inner:
          key:
            stagger: -5
            column_net: P19
      rows:
        bottom:
          row_net: P5
        home:
          row_net: P6
        top:
          row_net: P7
        num:
          row_net: P8
    thumbkeys:
      anchor:
        ref: matrixkeys_inner_bottom
        shift: [-kx, -ky-2.5]
      columns:
        near:
          key:
            column_net: P15
        home:
       #   key.splay: -5
          key:
            origin: [-11.75, -9]
            column_net: P18
        far:
         # key.splay: -5
          key:
            origin: [-9.5, -9]
            column_net: P19
      rows:
        cluster:
          row_net: P9
    palmkeys:
      anchor:
        ref: matrixkeys_outer_bottom
        shift: [0, -ky]
      columns:
        single:
          key:
            column_net: P0
      rows:
        cluster:
          row_net: P8
    screw_top_outer:
      key:
        width: 2
        height: 2
        rotate: 45
      anchor:
        ref: matrixkeys_outer_num
        shift: [kx/2, -ky/2+1.25]
    screw_bottom_outer:
      key:
        width: 2
        height: 2
        rotate: 45
      anchor:
        ref: matrixkeys_outer_bottom
        shift: [kx/2, -ky/2]
    screw_top_middle:
      key:
        width: 2
        height: 2
        rotate: 45
      anchor:
        ref: matrixkeys_middle_num
        shift: [-kx/2, -ky/2-1.25]
    screw_bottom_middle:
      key:
        width: 2
        height: 2
        rotate: 45
      anchor:
        ref: matrixkeys_middle_bottom
        shift: [-kx/2, -ky/2-2.5]
    screw_top_inner:
      key:
        width: 2
        height: 2
        rotate: 45
      anchor:
        ref: matrixkeys_inner_num
        shift: [kx/2, -ky/2]
    screw_bottom_inner:
      key:
        width: 2
        height: 2
        rotate: 45
      anchor:
        ref: matrixkeys_inner_bottom
        shift: [kx/2, -ky/2]
    mcu:
      key:
        width: 18
        height: 38
        mirror.skip: true
        rotate: 15
      anchor:
        shift: [37,16.5]
        ref: matrixkeys_inner_num
    trackpad:
      key:
        width: 65
        height: 50
        mirror:
          skip: true
        rotate: 15
      anchor:
        shift: [49.5, -32]
        ref: matrixkeys_inner_num


  rotate: -15
  mirror:
    ref: matrixkeys_inner_bottom
    distance: kx + 90

outlines:
  keys:
    - what: rectangle
      where: /key/
      bound: false
      size: [kx-1,ky-1]
      fillet: 2
  mcu:
    - what: rectangle
      where: /mcu/
      size: [18, 38]
  trackpad:
    - what: rectangle
      where: /trackpad/
      size: [65, 50]
      fillet: 2
  key_cutouts:
    - what: rectangle
      where: /key/
      size: [kcow, kcoh]
  screws:
    - what: circle
      where: /screw/
      radius: screw_radius
  board:
    - what: polygon
      operation: stack
      fillet: 4
      points:
        - ref: matrixkeys_outer_num
          shift: [-0.5px,0.5py]
        - ref: matrixkeys_ring_num
          shift: [0.4px,0.6py]
        - ref: matrixkeys_middle_num
          shift: [0.5px,0.5py]
        - ref: mirror_matrixkeys_middle_num
          shift: [0.5px,0.5py]
        - ref: mirror_matrixkeys_ring_num
          shift: [0.4px,0.6py]
        - ref: mirror_matrixkeys_outer_num
          shift: [-0.5px,0.5py]
        - ref: mirror_matrixkeys_outer_bottom
          shift: [-0.5px,-1.35py]
        - ref: mirror_thumbkeys_far_cluster
          shift: [0.5px,-0.5py]
        - ref: thumbkeys_far_cluster
          shift: [0.5px,-0.5py]
        - ref: matrixkeys_outer_bottom
          shift: [-0.5px,-1.35py]
  frontplate:
    - what: outline
      name: board
    - what: outline
      name: key_cutouts
      operation: subtract
    - what: outline
      name: screws
      operation: subtract
    - what: outline
      name: mcu
      operation: subtract
  backplate:
    - what: outline
      name: board
    - what: outline
      name: screws
      operation: subtract
  preview:
    - what: outline
      name: board
    - what: outline
      name: keys
      operation: stack
    - what: outline
      name: screws
      operation: stack
    - what: outline
      name: mcu
      operation: stack
    - what: outline
      name: trackpad
      operation: stack
pcbs:
  backplate:
    template: kicad8
    outlines:
      main:
        outline: backplate
    footprints:
      m2_screws:
        what: ceoloide/mounting_hole_npth
        where: /screw/
        params:
          hole_size: screw_diameter
          hole_drill: screw_diameter

  frontplate:
    template: kicad8
    outlines:
      main:
        outline: frontplate
    footprints:
      m2_screws:
        what: ceoloide/mounting_hole_npth
        where: /screw/
        params:
          hole_size: screw_diameter
          hole_drill: screw_diameter

  main_board:
    template: kicad8
    outlines:
      main:
        outline: board
    footprints:
      m2_spacers:
        what: ceoloide/mounting_hole_npth 
        where: /screw/
        params:
          hole_size: spacer_diameter
          hole_drill: spacer_diameter
      switches:
        what: ceoloide/switch_mx
        where: /key/
        params:
          include_keycap: true
          solder: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diodes:
        what: ceoloide/diode_tht_sod123
        where: /key/
        params:
          include_tht: true
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -7.5]
      mcu:
        what: ceoloide/mcu_supermini_nrf52840
        params:
          include_extra_pins: "true"
          reverse_mount: "true"
        where:
          ref.aggregate.parts: [matrixkeys_inner_num, mirror_matrixkeys_inner_num]
          shift: [0,8]
      battery_connector:
        what: ceoloide/battery_connector_jst_ph_2
        where:
          ref.aggregate.parts: [matrixkeys_inner_num, mirror_matrixkeys_inner_num]
          shift: [-20, 0]
      display:
        what: ceoloide/display_nice_view
        where:
          ref.aggregate.parts: [matrixkeys_inner_num, mirror_matrixkeys_inner_num]
          shift: [0, 5]
        params:
          include_courtyard: false
          include_silkscreen: true
          MOSI: P2
          SCK: P3
          CS: P1
      reset_button:
        what: ceoloide/reset_switch_smd_side
        where:
          ref.aggregate.parts: [matrixkeys_inner_num, mirror_matrixkeys_inner_num]
          shift: [20, 23]
      power_switch:
        what: ceoloide/power_switch_smd_side
        where:
          ref.aggregate.parts: [matrixkeys_inner_num, mirror_matrixkeys_inner_num]
          shift: [-20, 23]
          rotate: 90
      keep_out:
        what: ceoloide/utility_keepout_zone
        where:
          ref.aggregate.parts: [matrixkeys_inner_num, mirror_matrixkeys_inner_num]
        params:
          name: "trackpad"
          outline_type: "full"
          points: [[0,0],[65,0],[65,50],[0,50]]
      # TODO: trackpad, routing1